# Generated by Django 5.1.3 on 2025-07-20 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_name', models.CharField(max_length=100, unique=True)),
                ('shelf_code', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('form_class', models.CharField(blank=True, help_text='Form/class associated with this shelf.', max_length=50, null=True)),
                ('shelf_count', models.PositiveIntegerField(default=0, editable=False)),
                ('max_borrow_per_student', models.PositiveIntegerField(default=1, help_text='Maximum books a student can borrow from this shelf.')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=20)),
                ('class_teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('total_students', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'unique_together': {('form', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='RevisionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='revision_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publishers', models.CharField(blank=True, max_length=255, null=True)),
                ('first_publication', models.PositiveIntegerField(blank=True, null=True)),
                ('ISBN', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('book_number', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(editable=False, max_length=50)),
                ('book_picture', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_api.shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('admission_number', models.PositiveIntegerField(unique=True)),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('year_of_study', models.PositiveIntegerField(blank=True, null=True)),
                ('current_class', models.CharField(blank=True, max_length=50, null=True)),
                ('student_picture', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='library_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned', models.BooleanField(default=False)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.book')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_api.shelf')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_api.student')),
            ],
        ),
    ]
